# Generated by Django 5.1.1 on 2025-01-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="action",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="item",
            name="deadline",
            field=models.DateField(blank=True),
        ),
    ]
