# Generated by Django 5.1.1 on 2025-01-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_alter_item_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="action",
            field=models.CharField(max_length=30),
        ),
    ]
