# Generated by Django 5.1.1 on 2025-01-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_alter_item_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="action",
            field=models.CharField(max_length=26),
        ),
    ]
