# Generated by Django 5.1.1 on 2025-01-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0006_alter_item_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="action",
            field=models.CharField(max_length=28),
        ),
    ]
