# Generated by Django 5.1.1 on 2025-01-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invites", "0002_invite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invite",
            name="timestamp",
        ),
    ]
