# Generated by Django 5.1.1 on 2025-01-15 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invites", "0003_remove_invite_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invite",
            name="read",
        ),
        migrations.AddField(
            model_name="invite",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
