# Generated by Django 5.1.1 on 2025-01-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invites", "0004_remove_invite_read_invite_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
    ]
