# Generated by Django 5.1.1 on 2025-01-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event",
            field=models.CharField(max_length=24),
        ),
    ]
